### ISSUE TITLE
SharpKeys link

### ISSUE THREAD

**Issue by VeH-c** [DreymaR/colemak_org#3]
On https://dreymar.colemak.org/ergo-mods.html the link [Registry remapping](https://dreymar.colemak.org/www.randyrants.com/sharpkeys/) should point to https://github.com/randyrants/sharpkeys

**Comment by DreymaR** [comment]
Oh, thank you! I've changed the link to the official (or at least, the shortest and clearest) SharpKeys address, which is:

https://www.randyrants.com/sharpkeys/
